### ISSUE TITLE
Posting process and permissions for the VA Platform Documentation site

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#112]
## Considerations
- [platform website guidelines and process](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) for how to contribute to the platform website.
- [video tutorial on contributing to the platform website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1241579796/Organization)
- [frontend developer docs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/687931428/Frontend+developer+documentation) everything here gets published to the platform website. May be good to check if all FLT engineers have edit permissions here. 

- [x] Micah
- [x] Susanna
- [x] BJ
- [x] Komes

## Task Description
1. Investigate the approval process for posting content to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) and document what that process is. [KT: This site is managed by the Platform Content Team: https://vfs.atlassian.net/wiki/spaces/CIT/overview.]
2. Investigate the permissions that will be needed to post updated Forms Library help documentation to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) and assign those permissions to the appropriate members of the Forms Library Team.

## This is done when
- [ ] We know what the approval process is for adding new content to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).
- [ ] We know what permissions are needed to post to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).
- [ ] Permissions to post content to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) site have been assigned to the appropriate members of the Forms Library Team AND those members have confirmed that the permissions are working correctly.
- [ ] We have created a page in the Confluence FLT space that details the approval process for posting content on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) (OK if this points to another Confluence page that is the page of record for this information), the permissions needed to post content on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html), and how to request the permissions needed to post content on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).
