### ISSUE TITLE
Documentation Work: Overview

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#114]
## Task Description
1. Write, review, and post an Overview section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described in the New Documentation Outline/Blueprint created via ticket #113.

## Considerations
Think of this as a Beginner's Guide to Forms and the Forms Library.

This content should:
- Focus on helping people who are new to the Forms Library.
- Answer these questions: 
    - What is a form? (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2042200279/What+is+a+Form)
    - What is the Forms Library? (#75 will help with this) 
    - Why is the tool set up the way that it is? (to address the current shortcoming of "fair amount of what but no why.")
    - What does it do? 
    - When should it be used? (talk about use cases supported/not supported by Forms Library, maybe do this in a checklist format?)
    - When should a team consider just using the design system? (provide link(s) to relevant Design System documentation)
    - Make sure we explain the how the Forms Library relates to the Design System and what differentiates them.
- Communicate standards that the forms library adheres to, what to expect when a team chooses to use it.
- Encompass form building for paper to online scenarios AND native digital experiences

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] Overview draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] Overview content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2085355587/VA+Forms+System+Overview).
- [x] Overview content has been posted to the [Production VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html).

**Comment by bjmccotter7192** [comment]
https://vfs.atlassian.net/wiki/spaces/PWD/pages/2085355587/VA+Forms+System+Overview

**Comment by taylorkaren** [comment]
@bjmccotter7192: Is there any outdated content or other cleanup work we need to do as a follow on to this ticket?

**Comment by micahchiang** [comment]
LGTM! Left one comment about linking to the depo documentation for the yeoman generator.
