### ISSUE TITLE
Write Proposed Endgame States Summary Page for Fix vs Greenfield Decision

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#115]
## Task Description
Create a Confluence page that:
- [x] Provides links to the research work done on the current Forms Library and candidates to replace the current Forms Library (COTS, Open Source, the FLT POC), with links to the appropriate Confluence pages for full details.
- [x] Provides links to additional definition work on what is a form and fix v. greenfield analysis.
- [x] Lists potential endgame states for the new Forms System with a link to a details page for each endgame state.
- [x] Includes an executive summary of the endgame states.

This page, and the linked details pages, will be used to review findings with Kevin and Ryan and ask for a VA decision on the endgame and path to follow. That decision will then lead to the team developing details on what we would prototype first (June target time frame), what this team would be able to do by mid-September, and what a team would be doing beyond September.

## This is done when
- [x] There is a Confluence page that includes all of the information listed above in the Task Description section (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2077229071/Endgame+Scenarios+Summary)

All members of the Forms Library Team have reviewed and provided feedback (as applicable) and approval on the content of the pages:
- [x] BJ
- [x] Karen
- [x] Komes
- [x] Micah
- [x] Susanna

**Comment by kkomes** [comment]
On the risk factor. the tiered solution would have exactly the same risk as POC has for using the new schema. Because tiered will create new schema as well. Also with other security risk it should be the same.

**Comment by kkomes** [comment]
Sorry for the late addition. I have added two more pros to the POC proposal to distinguish between the POC and tiered solution. So you can update your summary.

- Save time on going through all the deployment procedures. It needs to be deployed only once. Any updates on the form will be pulled from the database.
- Keep track of forms. Easy to search and locate
