### ISSUE TITLE
Documentation Work: Using Forms in Production

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/formulate#117]
## Task Description
1. Write, review, and post a Using Forms in Production section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described in the New Documentation Outline/Blueprint created via ticket #113.

## Considerations
- [spreadsheet for doc migration](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0)
- [Current help content for Forms in Production](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/forms-in-production/)

This content should:
- [x] Mention the use of the migrations attribute on formConfig
- [x] Cover migrating forms into vets-json-schema
- [x] Cover updating the vets-website package.json dependency
- [x] Explain the vets-api Gemfile.lock entry
- [x] Include helpful examples and code snippets portraying use cases
- [x] Include links to code in vets-website where forms are using the features covered.
- [x] [Per this comment](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/349/files#r796817206), this content should go over best practices for working in vets-json-schema, particularly around importing and using things from the `/common` directory as much as possible. 

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] Using Forms in Production draft content has been written. (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2101543148/VA+Forms+System+-+Forms+in+Production)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] Using Forms in Production content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2101543148/VA+Forms+System+-+Forms+in+Production).
- [x] Using Forms in Production content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---Using-Forms-in-Production.2101543148.html)

**Comment by micahchiang** [comment]
Looks great! Nice work @bjmccotter7192 🚀

**Comment by taylorkaren** [comment]
@bjmccotter7192: The check box for "using things from the /common directory as much as possible" is not selected - does that mean you still need to add that content?
