### ISSUE TITLE
Documentation Work: Form Config Options

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/formulate#119]
## Task Description
1. Write, review, and post a Form Config Options section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described in the New Documentation Outline/Blueprint created via ticket #113.

## Considerations
 - [spreadsheet for doc migration](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0)
- [Form config options section](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/config-options) while this includes a lot of the options, there's a high chance some are missing.

This content should:
- Cover every config option available for use in the `formConfig` object
- Describe what each config option does.
- Include helpful examples and code snippets portraying use cases
- Include links to code in vets-website where forms are using the features covered.

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] Form Config Options draft content has been written (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2097381477/Form+Config+Options)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] Form Config Options content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2097381477/VA+Forms+System+-+Form+Config+Options)
- [x] Form Config Options content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---Form-Config-Options.2097381477.html).

**Comment by micahchiang** [comment]
Looks awesome @kkomes! I added a couple comments but that's it. Great work 🎉

**Comment by bjmccotter7192** [comment]
Looks good @kkomes I also added a couple of small comments to tweak but overall looks great!
