### ISSUE TITLE
Documentation Work: Component Hierarchy

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#128]
## Task Description
Write, review, and post a Component Hierarchy section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
 - [spreadsheet for doc migration](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0)
- [About the React component hierarchy on the current help site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/component-hierarchy/): rewrite this content (see list below for what content should include) and move to the new site.

This content should:
- Be reviewed and updated as needed when moving to the new site.

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] Component Hierarchy draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] Component Hierarchy content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2117206121/VA+Forms+System+-+About+the+React+component+hierarchy)
- [x] Component Hierarchy content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).

**Comment by sdk-irl** [comment]
Component hierarchy is here: https://vfs.atlassian.net/l/c/8MQsT6ek

**Comment by micahchiang** [comment]
LGTM! Nice work @sdk-irl

**Comment by sdk-irl** [comment]
Feedback from @taylorkaren fixed, though there is some question based on today's discussion what will happen with the links once published. Left the TOC out since that will be added automatically when published

**Comment by bjmccotter7192** [comment]
LGTM! Good job on this one.
