### ISSUE TITLE
Documentation Work: How to manage array based data using “list loops”

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#139]
**_Sprint Planning, 2/15/22: Assume that this is about half a sprint's worth of work._**

## Task Description
Write, review, and post a How to manage array based data using “list loops” section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
- [Existing documentation on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/list_loop.md): **_NOTE that this is a start, but needs work. Look at reorganizing, rewriting, and links to examples on the live site as improvement areas._**

This content should:
- Clearly explain what a list loop is practically and technically (schema with type array under the hood)
- Clearly explain when list loops should be used 
- Clearly explain how to implement the list loop code (a step by step example might be good here)
- Clearly explain how to reference items within a list (an index argument is available through things like updateSchema and replaceSchema, as well as a couple of other helper functions)
- Provide links to good list loop examples on the live site
    - Consider linking to the 686c-674 add spouse and add child workflows for examples of list loops

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to manage array based data using “list loops” content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] How to manage array based data using “list loops” content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2101805082/VA+Forms+System+-+Working+with+Array+Data+aka+List+Loops)
- [x] How to manage array based data using “list loops” content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---How-to-work-with-Array-Data-(aka-List-Loops).2101805082.html)

**Comment by micahchiang** [comment]
https://vfs.atlassian.net/wiki/spaces/FLT/pages/2101805082/Working+with+array+data+in+the+forms+library+WIP
