### ISSUE TITLE
Include any old Documentation PR changes in new doc effort?

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#140]
## Task Description/This is done when
- [x] Review the comments generated on ticket #116.
- [x] If any changes associated with the PR referenced on ticket #116 are relevant and NOT included on any of the Documentation work tickets we have already written, write a ticket to do that work.
- [x] Add a comment on the original PR with a reference to the ticket number we have written and what change(s) on that original PR will be addressed by the new ticket.

**Comment by micahchiang** [comment]
Added comment to #117 that referenced [this comment](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/349/files#r796817206) around using definitions in the `/common` directory in vets-json-schema

**Comment by micahchiang** [comment]
Went through the old PR. Nothing warranted it's own ticket, and I've updated #117 with a comment to mention pulling things from `/common` as much as possible.
