### ISSUE TITLE
Establish transition plan for FLT to take over forms library support tickets

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/formulate#153]
## Description
The DST currently presides over all support tickets that come in through slack that concern the forms library. Our team should take over this part of the rotation for two reasons: 
1. We are the forms library team and should be the initial source of authority on things related to our subject area
2. Seeing support tickets firsthand will surface issues or areas we should consider when building a new forms library

## Considerations
- A clear communication strategy that goes out to application teams should be crafted to include:
    - Our intentions: active development on the current forms library will end. Unless there are production breaking bugs uncovered, active feature iteration is ending.
    - Support requests that are around "how to do a thing in the forms library" will be time boxed (amount of time tbd)
    - App teams should have clear expectations set for them that the current forms library is officially in maintenance mode. Teams are still welcomed to use it to achieve roadmap OKRs, but again, feature requests will not be worked on. 
- FLT will need to be added to the support rotation and we will need to establish a support cadence where each member rotates onto support for x amount of time. Support rotation should include guidance on how to time box issues, where to send people for documentation, etc.

## Tasks
- [ ] Craft communication strategy
- [ ] Coordinate with DST on transition timeline, pick a date and work backward
- [ ] Establish FLT support rotation 

## Acceptance Criteria
- [ ] Comm strategy has been created, finalized, and committed to confluence
- [ ] Transition date has been established for when FLT will assume responsibility for forms library tickets
- [ ] FLT support rotation has been established and committed to confluence
