### ISSUE TITLE
Architectural Decision Document

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#155]
## Task Description
Per Kevin: "Micah will need to submit an Architectural Decision doc...he can sync with @mchelen directly for guidance on templates, etc."

## Considerations
- Draft document here: https://vfs.atlassian.net/wiki/spaces/ECP/pages/2103836726/%5BDRAFT%5D+Rewrite+the+Forms+Library

## This is done when
- [ ] We confirm that Michael Chelen has reviewed the doc
- [ ] Document reflects the decision we have to go forward
- [ ] Document has been shared via Platform Office Hours

## Reviewed by
- [x] BJ
- [x] Karen
- [x] Micah
- [x] Komes
- [x] Susanna

**Comment by micahchiang** [comment]
https://vfs.atlassian.net/wiki/spaces/ECP/pages/2103836726/DRAFT+Rewrite+the+Forms+Library
