### ISSUE TITLE
Synthesize past research and user journeys that Carol Wong shared in forms library channel in DSVA slack

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#64]
## Task Description
The team will explore and synthesize existing user journeys, customer survey results, and past research on the forms library to complement round 1 of our discovery research. 

## Acceptance Criteria
- [ ] Synthesize 2020 and 2021 quarterly feedback themes
- [ ] Synthesize existing designer and engineer user journey maps shared by [Carol Wong](https://dsva.slack.com/archives/C02L9109NMQ/p1638810754144700) and in [Confluence] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1716650105/User+Journey+Maps)
- [ ] Audit Confluence for past research related to forms library and synthesize (this page seems to be where the Design System Team is collecting their research: https://vfs.atlassian.net/wiki/spaces/DST/pages/1868791871/Design+system+research)
- [ ] Add all findings to [Confluence Past Research synthesis](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2018181452/Sound+bites+from+prior+DST+research+WIP.)

**Comment by ken-non** [comment]
should be refined to #73

**Comment by ken-non** [comment]
will be added to past research synthesis confluence

**Comment by taylorkaren** [comment]
This work was done and reflected in the work product created via ticket #73.
