### ISSUE TITLE
Onboard new researcher

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#65]
## Task Description
Onboard Brittany Iannuzzi to the Forms Library Team

## Acceptance Criteria
- [x] Add Brittany to DSVA slack channels
- [x] Get VFS Confluence access
- [x] Get VA Github access. [Request ticket here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/9101)
- [x] Complete Liberty onboarding paperwork
