### ISSUE TITLE
(Please review for BJ) Current Forms Library Audit

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#75]
## Task Description
- Compile an audit of what is included in the current Forms Library.
- Answer these questions:
-- Are all of these things needed?
-- Is anything missing?
- Document where the Forms Library ends and other Design System items begin and what overlap exists between the Forms Library and other Design system elements
-- Validating this diagram (and updating as needed) should be part of this task: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1604621450055/a82730cf9ad27d35a837bb54c17660a531eef1bf?sender=u7b7ab34685f00706a24a6128

### Why this?
This is another task that will help us understand the state of the current Forms Library and the pros and cons of continuing to use it or move to a new system.

## Acceptance Criteria
- [x] Research has been synthesized into a Confluence document in the FLT workspace
- [x] That Confluence document includes an inventory of the Forms Library elements with an assessment on whether each element is needed as is, needed but would benefit from some modification/refactoring, or not needed (with thoughts on how deprecation might be handled).
- [x] That Confluence document also includes a list of any elements that are not included but would be beneficial to add, with thoughts on how the addition might be handled.
- [x] That Confluence document also includes documentation on where the Forms Library ends and other Design System items begin and what overlap exists between the Forms Library and other Design system elements.

### Documentation is reviewed and accepted by:
- [x] Micah Chiang 
- [x] Komes Komes 
- [x] BJ McCotter 
- [x] Susanna Kline 
- [x] Karen Taylor / Kennon Hulett

**Comment by micahchiang** [comment]
Existing doc on forms library routing - https://vfs.atlassian.net/wiki/spaces/FLT/pages/2002354239/Forms+Library+routing+research+notes

**Comment by taylorkaren** [comment]
BLOCKER: Mural Board link is not accessible - redirecting to another URL.

**Comment by taylorkaren** [comment]
Confluence page: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2031812688/Current+Forms+Library+Audit.

**Comment by bjmccotter7192** [comment]
I believe I have compiled a good starting audit for the Form System and the overlap of the design system elements used in Forms located in the 'applications' directory of vets-website. Would like someone to review and get some feedback if possible and I will make edits.
