### ISSUE TITLE
Update Formulate repository

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/formulate#76]
## Description
There are several updates to the Formulate repository that should happen to reflect a more product oriented initiative:
- Renaming the repository itself from formulate to forms-library
- Updating the readme so it contains any new information
- Updating the About section to make it clear that this repo is for new Forms Library work, it is not something currently in use.

## Considerations
- Renaming the repository itself may have downstream implications: npm publishing, vets-website dependency etc. Will need to weigh whether or not a rename is worth the effort here.

## Tasks
- [ ] Repo has been renamed *if* the effort isn't terribly high
- [ ] Readme has been updated to reflect new information 
- [ ] About section has been updated to reflect new information

**Comment by taylorkaren** [comment]
Superseded by ticket #150.
