### ISSUE TITLE
Review the new Forms Library Tech Design

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#78]
## Task Description
Review the New Forms Library Tech Design (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2021-05-18-forms-library.md) to assess the delta between what is described here and what exists in the current code base for the new Forms Library.

[Confluence Doc](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2025029667/Forms+Library+Design+Document+WIP)

### Why this?
- So that we have an understanding of what the original intent was for the new Forms Library and can have informed conversations with the Design System Team about the intended design and the coding that got started on this effort.

### Considerations
- Copy and paste this content into a Confluence page to update and comment as we review. 
- Add text at the top of the current GitHub page to note that updates to the document are now being done in Confluence and provide a link to the Confluence page on the GitHub page.

## Acceptance Criteria
- [ ] The new Forms Library tech design has been reviewed by all engineering team members and review notes are synthesized in a Confluence document in the FLT workspace. 
- [ ] The GitHub page with the original content for the new tech design has a message noting that the content on that page is now outdated with a link to the Confluence page where the content now resides.

### Documentation is reviewed and accepted by:
- [x] Micah Chiang 
- [x] Komes Komes 
- [x] BJ McCotter 
- [x] Susanna Kline 
- [x] Karen Taylor / Kennon Hulett
