### ISSUE TITLE
Review COTS Form Building Apps

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#82]
## Task Description
- Compile an inventory of Commercial Off the Shelf (COTS) Form Building Apps and assess how many of the core VA form builder requirements each one meets.

### Why this?
This is one of the potential solution paths included on the [Roadmap](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992589392/Roadmap+Draft+Provisional) and this inventory will give us a starting point if we choose to pursue further research on this approach.

## Acceptance Criteria
- [x] Research has been synthesized into a Confluence document in the FLT workspace
- [x] That Confluence document includes a list of apps that were reviewed with details on how many of the core VA form builder capabilities are met by each app.
- [x] The URL for the Confluence document is included as a comment on this issue.

**Comment by taylorkaren** [comment]
Work in progress on this Confluence page: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2018279425/COTS+Form+Building+Review.
