### ISSUE TITLE
(Reviews Needed) Review Open Source Form Building Candidates

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#83]
## Task Description
- Compile an inventory of Open Source Form Building apps/frameworks/platforms and assess how many of the core VA form builder requirements each one meets.

## Considerations
- Use the [COTS Form Building Review page ](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2018279425/COTS+Form+Building+Review) as a model for evaluation criteria and information structure.
-- There are two open source entries on the COTS page (Budibase and Form.io) that could be moved to this inventory.
- Susanna's research on react-hook-forms (#81) should also be incorporated in these review findings.
- Should we be looking at Drupal modules as part of this assessment? 
-- Drupal is the CMS for Va.gov, but it is also a specific technology stack and that would make any Drupal module forms solution tied to that.
- Look into the current version of the US Web Design System (US WDS - https://designsystem.digital.gov/) and assess how it matches to the evaluation criteria.

### Why this?
This is one of the potential solution paths included on the [Roadmap](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992589392/Roadmap+Draft+Provisional) and this inventory will give us a starting point if we choose to pursue further research on this approach.

## Acceptance Criteria
- [x] Research has been synthesized into a Confluence document in the FLT workspace
- [x] That Confluence document includes a list of apps/frameworks/platforms that were reviewed with details on how many of the core VA form builder requirements is met by each app/framework/platform.
- [x] The URL for the Confluence document is included as a comment on this issue.

[Documentation](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2044952577/Review+Open+Source+Form+Building+Candidates) is reviewed and accepted by:
- [x] Micah Chiang 
- [x] Komes Komes 
- [x] BJ McCotter 
- [x] Susanna Kline 
- [x] Karen Taylor / Kennon Hulett

**Comment by ken-non** [comment]
@kkomes to add confluence link

**Comment by kkomes** [comment]
Confluence page: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2044952577/Review+Open+Source+Form+Building+Candidates

**Comment by ken-non** [comment]
confluence in progress

**Comment by taylorkaren** [comment]
Reviewed the Confluence page and posted a couple of comments. Will check off acceptance when comments are resolved.

**Comment by kkomes** [comment]
The document has been updated.

**Comment by taylorkaren** [comment]
Updates look good - thanks, @kkomes!

**Comment by micahchiang** [comment]
Looks great @kkomes! Thanks for the thorough research! 🎉
