### ISSUE TITLE
Documentation Work: Getting Started with the Forms Library

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#91]
## Task Description
1. Write, review, and post a Getting Started with the Forms Library section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described in the New Documentation Outline/Blueprint created via ticket #113.

## Document Link
[VAFS - Getting Started](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS+Draft)

## Considerations
- Review existing Forms Library tutorial documentation (https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/form-tutorial-basic, and other pages listed under the Tutorial menu on the left side of this page)
- Identify errors in the current tutorial documentation, make a list of what they are and how to address them
- Identify gaps to address in the current tutorial documentation related to why and when you would use the Forms Library 
- Identify gaps to address in the current tutorial documentation related to background information, context, and why you would use specific elements of the Forms Library
- Review the [Gotchas page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2010382387/Forms+Library+Gotcha+s+and+Helpful+Tips) for information that will be helpful to include in the revised Getting Started Guide.
- Review the research found in the [Engineering Docs section of Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1998749743/Engineering+Docs) for additional information that would be helpful to include in the revised Getting Started Guide.
- Re-implement the tutorial sections as a Getting Started with the Forms Library guide that assumes you know nothing about working with the Forms Library and provides an accurate, step by step walkthrough on how to set up a new form, how to add form components from the Forms Library, how to add web components from the Design System Components library, how to work with the schema, and other common form-building tasks.

Content should include:
- getting started using the Yeoman application generator
- brief summary of schema and uiSchema (can point to full information about scheme and uiSchema to be developed on ticket #120)

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] Getting Started with the Forms Library draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] Getting Started with the Forms Library content has been posted to the [Draft VA Platform Documentation site - VAFS - Getting Started](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS+Draft).
- [x] Getting Started with the Forms Library content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---Getting-Started-with-VAFS.2104197265.html).

**Comment by micahchiang** [comment]
LGTM! Nice work @bjmccotter7192 Just left one comment about adding a screenshot and provided a link to a form you can use on staging without logging in.

**Comment by bjmccotter7192** [comment]
All done and in production, moving to closed.
