### ISSUE TITLE
Establish metrics and associated measurements for Q1 Objective KRs

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#94]
## Task Description

1. Review the initial KRs defined for each Q1 Objective and determine if we have a means to measure a meaningful metric for those KRs.
- If Yes, detail the measurement for each KR.
- If No, research needed to determine what we can measure and potentially revise the KRs. Discuss findings with Ryan for approval to change, if applicable.

Update the appropriate documentation when we have finalized the KRs and associated metrics:
- [x] Platform page at https://vfs.atlassian.net/wiki/spaces/AP/pages/2012086329/Crew+Teams#Forms-Library-Team
- [x] FLT Roadmap page - excerpt from Platform Page and text on this page (https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992589392/Roadmap)
- [x] FLT Overview page - excerpt from Platform Page and text on this page, especially the Metrics info (https://vfs.atlassian.net/wiki/spaces/FLT/overview?homepageId=1992458316)

**Comment by taylorkaren** [comment]
Lauryl's research and proposed revision to KR text can be found on the [Baseline KRs page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2051538980/Baseline+KRs)
